### ISSUE TITLE
image does not run on CentOS7

### ISSUE THREAD

**Issue by kvashishta** [btorresgil/docker-splunk#1]
I could successfully build an image. I had to copy /usr/sbin/init into the directory of the Dockerfile.

I have however not been able to run the image, this is the error I receive:

Successfully built 65dc557b27c2
[root@test232 splunk]# docker run 65dc557b27c2
/bin/bash: /init/start: No such file or directory

**Comment by btorresgil** [comment]
Hi and thanks for opening the issue.  This image has been deprecated in favor of the now official Splunk docker image.  You can get the official Splunk image from docker hub:  https://hub.docker.com/r/splunk/splunk/
